#!/usr/bin/env bash
set -Eeuo pipefail
ROOT=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)
if [[ $(id -u) -eq 0 ]]; then echo "Do not compile as root. Run this command without sudo." >&2;exit 1;fi
mkdir -p "$ROOT/logs" "$ROOT/dist"
LOG="$ROOT/logs/build-$(date +%Y%m%d-%H%M%S).log"
exec > >(tee "$LOG") 2>&1
trap 'status=$?; echo "Build stopped (exit $status). Log: $LOG"; echo "No existing Win RDP installation was changed."; exit $status' ERR
if [[ ${1:-} == --check ]]; then python3 "$ROOT/scripts/preflight.py";exit;fi
python3 "$ROOT/scripts/preflight.py"
JOBS=${WINRDP_JOBS:-4}
[[ $JOBS =~ ^[1-9][0-9]*$ ]] || { echo 'WINRDP_JOBS must be a positive integer';exit 1; }
# Pin the dependency resolution generated by the first successful registry resolution.
# No fabricated Cargo.lock is shipped when registry access is unavailable.
if [[ ! -f "$ROOT/src-tauri/Cargo.lock" ]];then
  echo "Resolving Rust dependencies for the first build; keep the resulting Cargo.lock."
  cargo generate-lockfile --manifest-path "$ROOT/src-tauri/Cargo.toml"
fi
export CARGO_TARGET_DIR=${CARGO_TARGET_DIR:-"$ROOT/src-tauri/target"}
cargo test --manifest-path "$ROOT/src-tauri/Cargo.toml" --release --locked --jobs "$JOBS"
cargo build --manifest-path "$ROOT/src-tauri/Cargo.toml" --release --locked --jobs "$JOBS"
export CARGO_TARGET_DIR=${CARGO_TARGET_DIR:-"$ROOT/src-tauri/target"}
BINARY="$CARGO_TARGET_DIR/release/winrdp-next"
"$BINARY" --version
# Session windows are separate IronRDP-powered processes; build them alongside the launcher.
cargo build --manifest-path "$ROOT/session/Cargo.toml" --release --locked --jobs "$JOBS"
SESSION="$CARGO_TARGET_DIR/release/winrdp-session"
python3 "$ROOT/scripts/package-binary.py" --binary "$BINARY" --session "$SESSION" --out "$ROOT/dist"
echo "Binary package created in $ROOT/dist. Build success is not a live RDP test."
PACKAGE=$(ls -t "$ROOT"/dist/winrdp-next_*_"$(dpkg --print-architecture)".deb | head -1)
echo "Install with: sudo apt install $PACKAGE"
