#!/usr/bin/env bash
set -Eeuo pipefail
ROOT=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)
if [[ $(id -u) -eq 0 ]]; then echo "Do not compile as root. Run this command without sudo." >&2;exit 1;fi
mkdir -p "$ROOT/logs" "$ROOT/build" "$ROOT/dist"
LOG="$ROOT/logs/build-$(date +%Y%m%d-%H%M%S).log"
exec > >(tee "$LOG") 2>&1
trap 'status=$?; echo "Build stopped (exit $status). Log: $LOG"; echo "No existing Win RDP installation was changed."; exit $status' ERR
if [[ ${1:-} == --check ]]; then python3 "$ROOT/scripts/preflight.py";exit;fi
python3 "$ROOT/scripts/preflight.py" --write-env "$ROOT/build/environment.json"
readarray -t VALUES < <(python3 - "$ROOT/build/environment.json" <<'PY'
import json,sys
v=json.load(open(sys.argv[1]));print(v['runtime']);print(v['pkg_config_path'])
PY
)
RUNTIME=${VALUES[0]};export PKG_CONFIG_PATH=${VALUES[1]}
if [[ -n $RUNTIME ]];then
  export CMAKE_PREFIX_PATH="$RUNTIME"
  export LD_LIBRARY_PATH="$RUNTIME/lib:$RUNTIME/lib64${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"
fi
export WINRDP_NATIVE_BUILD="$ROOT/build/native"
JOBS=${WINRDP_JOBS:-4}
[[ $JOBS =~ ^[1-9][0-9]*$ ]] || { echo 'WINRDP_JOBS must be a positive integer';exit 1; }
cmake -S "$ROOT/native" -B "$WINRDP_NATIVE_BUILD" -G Ninja \
  -DCMAKE_BUILD_TYPE=Release -DCMAKE_SUPPRESS_REGENERATION=ON -DBUILD_TESTING=ON
cmake --build "$WINRDP_NATIVE_BUILD" --parallel "$JOBS"
ctest --test-dir "$WINRDP_NATIVE_BUILD" --output-on-failure --timeout 90
# Pin the dependency resolution generated by the first successful registry resolution.
# No fabricated Cargo.lock is shipped when registry access is unavailable.
if [[ ! -f "$ROOT/src-tauri/Cargo.lock" ]];then
  echo "Resolving Rust dependencies for the first build; keep the resulting Cargo.lock."
  cargo generate-lockfile --manifest-path "$ROOT/src-tauri/Cargo.toml"
fi
export CARGO_TARGET_DIR=${CARGO_TARGET_DIR:-"$ROOT/src-tauri/target"}
cargo build --manifest-path "$ROOT/src-tauri/Cargo.toml" --release --locked --jobs "$JOBS"
export CARGO_TARGET_DIR=${CARGO_TARGET_DIR:-"$ROOT/src-tauri/target"}
BINARY="$CARGO_TARGET_DIR/release/winrdp-next"
"$BINARY" --version
# Session windows are separate IronRDP-powered processes; build them alongside the launcher.
cargo build --manifest-path "$ROOT/session/Cargo.toml" --release --locked --jobs "$JOBS"
SESSION="$CARGO_TARGET_DIR/release/winrdp-session"
python3 "$ROOT/scripts/package-binary.py" --binary "$BINARY" --session "$SESSION" --runtime "$RUNTIME" --out "$ROOT/dist"
echo "Binary package created in $ROOT/dist. Build success is not a live RDP test."
echo "Install with: sudo apt install $ROOT/dist/winrdp-next_0.7.4_$(dpkg --print-architecture).deb"
